server:
  port: 8082
  servlet:
    context-path: /customer

eureka:
  client:
    serviceUrl:
      defaultZone: https://herokueurekaserviceanddis.herokuapp.com/eureka
    instance:
    preferIpAddress: true

spring:
  application:
    name: customer-service

datasource:
    url: jdbc:h2:file:/tmp/testdb;AUTO_SERVER=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10

jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    format-sql: true

h2:
    console:
      enabled: true

liquibase:
    enabled: true
    change-log: database/liquibase-changelog.xml

logging:
  level:
    liquibase: INFO
