server:
  port: 8082
  servlet:
    context-path: /customer

eureka:
  client:
    serviceUrl:
      defaultZone: https://herokueurekaserviceanddis.herokuapp.com

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://${DBHOSTNAME}:3306/${DBSCHEMA}
    username: ${DBUSERNAME}
    password: ${DBPASSWORD}
    hikari: 
     maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: database/liquibase-changelog.xml

logging:
  level:
    liquibase: INFO
