server:
  port: 8082
  servlet:
    context-path: /customer

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8080/eureka
    instance:
    preferIpAddress: true

spring:
  application:
    name: customer-service

datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10

jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    format-sql: true

h2:
    console:
      enabled: true

liquibase:
    enabled: true
    change-log: database/liquibase-changelog.xml

logging:
  level:
    liquibase: INFO
